version: '3.4'
services:
  memorizing_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - '45432:5432'
    networks:
      - shared_netschool_net
    volumes:
      - '~/.docker-conf/postgresql/data/:/var/lib/postgresql/data'
      - /var/lib/postgresql/data
  memorizing_rabbitmq:
    ports:
      - '5672:5672'
      - '5673:5673'
      - '15672:15672'
    networks:
      - shared_netschool_net
    volumes:
      - /var/lib/rabbitmq
  memorizing_api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '10000:8080'
    networks:
      - shared_netschool_net
    env_file:
      - env.api
  dsrnetschool_worker_1:
    networks:
      - shared_netschool_net
    ports:
      - '10001:8080'
    env_file:
      - env.worker
  memorizing_identity:
    ports:
      - '10003:8080'
    networks:
      - shared_netschool_net
    env_file:
      - env.identity
  memorizing_blazorapp:
    build:
      context: .
      dockerfile: Systems/Web/NetSchool.Web/Dockerfile
    networks:
      - shared_netschool_net
    volumes:
      - 'client_static:/app/publish/wwwroot:ro'
  redis:
    networks:
      - shared_netschool_net
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - '$PWD/redis-data:/var/lib/redis'
      - '$PWD/redis.conf:/usr/local/etc/redis/redis.conf'
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
  reverse_proxy:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - 'client_static:/usr/share/nginx/html:ro'
    depends_on:
      - memorizing_api
      - memorizing_identity
      - memorizing_blazorapp
    networks:
      - shared_netschool_net
networks:
  shared_netschool_net:
    name: net_school
    driver: bridge
volumes:
  client_static: null
